apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config-base
  namespace: default
data:
  ENV_TYPE: "base"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  ISTIO_VERSION: "1.20"
  AT_PROTOCOL_VERSION: "latest"
  REMIX_VERSION: "${REMIX_VERSION}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: environment-routing-base
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - mesh
  http:
  - name: "default-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: remix-ssr-service
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s 