apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config-dev
  namespace: default
data:
  ENV_TYPE: "development"
  LOG_LEVEL: "debug"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  DEBUG_MODE: "true"
  HOT_RELOAD: "true"
  WATCH_MODE: "true"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: environment-routing-dev
  namespace: default
spec:
  hosts:
  - "dev.app.local"
  gateways:
  - dev-gateway
  http:
  - name: "dev-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: remix-ssr-service
        subset: development
        port:
          number: 80
    timeout: 60s  # Longer timeout for development
    retries:
      attempts: 2
      perTryTimeout: 30s
    headers:
      response:
        add:
          x-environment: "development"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: dev-security-policy
  namespace: default
spec:
  selector:
    matchLabels:
      environment: development
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/developer"]
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"] 