apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config-prod
  namespace: default
data:
  ENV_TYPE: "production"
  LOG_LEVEL: "warn"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  CACHE_ENABLED: "true"
  CDN_ENABLED: "true"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: environment-routing-prod
  namespace: default
spec:
  hosts:
  - "app.com"
  gateways:
  - prod-gateway
  http:
  - name: "prod-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: remix-ssr-service
        subset: production
        port:
          number: 80
    timeout: 15s
    retries:
      attempts: 3
      perTryTimeout: 5s
    headers:
      response:
        add:
          strict-transport-security: "max-age=31536000; includeSubDomains"
          x-content-type-options: "nosniff"
          x-frame-options: "DENY"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prod-security-policy
  namespace: default
spec:
  selector:
    matchLabels:
      environment: production
  rules:
  - from:
    - source:
        namespaces: ["production"]
        principals: ["cluster.local/ns/production/*"]
  - to:
    - operation:
        methods: ["GET", "POST"]
        paths: ["/*"] 