apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config-staging
  namespace: default
data:
  ENV_TYPE: "staging"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  STAGING_FEATURES: "true"
  DATA_SYNC_ENABLED: "true"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: environment-routing-staging
  namespace: default
spec:
  hosts:
  - "staging.app.com"
  gateways:
  - staging-gateway
  http:
  - name: "staging-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: remix-ssr-service
        subset: staging
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
    headers:
      response:
        add:
          x-environment: "staging"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: staging-security-policy
  namespace: default
spec:
  selector:
    matchLabels:
      environment: staging
  rules:
  - from:
    - source:
        namespaces: ["staging"]
        principals: ["cluster.local/ns/staging/*"] 