runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  REMIX_CONFIG_PATH: "remix.config.cjs"
  NODE_ENV: "production"

handlers:
  - url: /build/(.*)
    static_files: build/\1
    upload: build/.*
    secure: always
    mime_type: application/javascript

  - url: /.*
    script: auto
    secure: always

  - url: /google4a0ee4a602388e0a\.html
    static_files: public/google4a0ee4a602388e0a.html
    upload: public/google4a0ee4a602388e0a\.html 