/** @type {import('@remix-run/dev').AppConfig} */
export default {
  appDirectory: 'app',
  assetsBuildDirectory: 'public/build',
  future: {
    v3_fetcherPersist: true,
    v3_relativeSplatPath: true,
    v3_throwAbortReason: true,
  },
  publicPath: '/build/',
  serverBuildPath: 'build/server/index.js',
  serverModuleFormat: 'esm',
  plugins: [require('@remix-run/eslint-config/patch/modern-browsers')],
  serverDependenciesToBundle: [
    '@remix-run/dev',
    '@remix-run/eslint-config',
    '@remix-run/node',
    '@remix-run/react',
    '@remix-run/serve',
    '@remix-run/web-fetch',
    '@remix-run/cloudflare',
    '@remix-run/cloudflare-pages',
  ],
  ignoredRouteFiles: ['**/*'],
  server: './server.ts',
  watchPaths: ['app/entry.server.tsx'],
  devServerBroadcastDelay: 1000,
  tailwind: true,
  css: {
    preprocessor: 'postcss',
    postcss: true,
  },
  serverMainFields: ['main', 'module'],
  serverBuildTarget: 'server',
  serverMinify: true,
  serverMinifyOptions: {
    compress: true,
    ecma: 2020,
    mangle: true,
    module: true,
    toplevel: true,
    keep_classnames: true,
    keep_fnames: true,
  },
  serverPlatform: 'neutral',
  serverRuntime: 'node',
  serverModuleFormat: 'esm',
  serverConditions: ['worker', 'browser'],
};
