apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = false

    [auth.google]
    enabled = true
    client_id = ${GOOGLE_CLIENT_ID}
    client_secret = ${GOOGLE_CLIENT_SECRET}
    allowed_domains = gobeze.ai
    allow_sign_up = true

    [security]
    admin_user = admin
    admin_password = ${GRAFANA_ADMIN_PASSWORD}

    [server]
    root_url = https://monitoring.gobeze.ai

    [dashboards]
    default_home_dashboard_path = /etc/grafana/dashboards/home.json 