apiVersion: v1
kind: Service
metadata:
  name: ai-metrics-exporter
  namespace: monitoring
  labels:
    app: ai-metrics-exporter
spec:
  ports:
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: ai-metrics-exporter 