apiVersion: v1
kind: Service
metadata:
  name: rag-metrics-exporter
  namespace: monitoring
  labels:
    app: rag-metrics-exporter
spec:
  ports:
  - port: 9091
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: rag-metrics-exporter 