apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-ai-model-filters
  namespace: logging
data:
  ai-model.conf: |
    # Model serving metrics
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key timestamp
          types inference_time:float,memory_usage:float,gpu_utilization:float
        </pattern>
      </parse>
      tag model_serving
    </filter>

    # Model performance metrics
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        model_version ${record.dig("message", "model_version") || "unknown"}
        model_type ${record.dig("message", "model_type") || "unknown"}
        inference_time ${record.dig("message", "inference_time_ms")}
        memory_usage ${record.dig("message", "memory_usage_mb")}
        gpu_utilization ${record.dig("message", "gpu_utilization_percent")}
        batch_size ${record.dig("message", "batch_size")}
        cache_hit_rate ${record.dig("message", "cache_hit_rate")}
        model_drift_score ${record.dig("message", "drift_score")}
      </record>
    </filter>

    # A/B testing metrics
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        experiment_id ${record.dig("message", "experiment_id")}
        variant ${record.dig("message", "variant")}
        success_rate ${record.dig("message", "success_rate")}
        latency_improvement ${record.dig("message", "latency_improvement")}
        quality_delta ${record.dig("message", "quality_delta")}
      </record>
    </filter> 