apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-code-generation-filters
  namespace: logging
data:
  code-generation.conf: |
    # Code generation quality metrics
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key timestamp
          types generation_time:float,accuracy_score:float
        </pattern>
      </parse>
      tag code_generation
    </filter>

    # Code generation metrics
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        generation_type ${record.dig("message", "generation_type") || "unknown"}
        code_language ${record.dig("message", "language") || "unknown"}
        generation_time ${record.dig("message", "generation_time_ms")}
        accuracy_score ${record.dig("message", "accuracy_score")}
        test_coverage ${record.dig("message", "test_coverage")}
        code_quality_score ${record.dig("message", "quality_score")}
        project_context_size ${record.dig("message", "context_size_bytes")}
      </record>
    </filter> 