apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-code-analysis-filters
  namespace: logging
data:
  code-analysis.conf: |
    # Code analysis logs
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key timestamp
          types analysis_duration:float,complexity_score:float
        </pattern>
      </parse>
      tag code_analysis
    </filter>

    # Code metrics
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        code_language ${record.dig("message", "language") || "unknown"}
        analysis_duration ${record.dig("message", "analysis_duration_ms")}
        complexity_score ${record.dig("message", "complexity_score")}
        code_quality_metrics ${record.dig("message", "quality_metrics")}
        security_issues ${record.dig("message", "security_findings")}
      </record>
    </filter> 