apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-performance-filters
  namespace: logging
data:
  performance.conf: |
    # Performance metrics
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key timestamp
          types response_time:float,memory_usage:float,cpu_usage:float
        </pattern>
      </parse>
      tag performance
    </filter>

    # Resource utilization
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        component_name ${record.dig("message", "component_name")}
        response_time ${record.dig("message", "response_time_ms")}
        memory_usage ${record.dig("message", "memory_usage_mb")}
        cpu_usage ${record.dig("message", "cpu_usage_percent")}
        thread_count ${record.dig("message", "thread_count")}
        garbage_collection_time ${record.dig("message", "gc_time_ms")}
        cache_size ${record.dig("message", "cache_size_mb")}
        queue_length ${record.dig("message", "queue_length")}
      </record>
    </filter>

    # Optimization metrics
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        optimization_type ${record.dig("message", "optimization_type")}
        improvement_percentage ${record.dig("message", "improvement_percent")}
        resource_savings ${record.dig("message", "resource_savings")}
        optimization_impact ${record.dig("message", "impact_score")}
      </record>
    </filter> 