apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-project-management-filters
  namespace: logging
data:
  project-management.conf: |
    # Project planning logs
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key timestamp
          types planning_duration:float
        </pattern>
      </parse>
      tag project_management
    </filter>

    # Project metrics
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        project_phase ${record.dig("message", "phase") || "unknown"}
        planning_duration ${record.dig("message", "planning_duration_ms")}
        feature_count ${record.dig("message", "feature_count")}
        dependency_count ${record.dig("message", "dependency_count")}
        estimated_completion ${record.dig("message", "estimated_completion")}
        actual_completion ${record.dig("message", "actual_completion")}
        accuracy_rate ${record.dig("message", "planning_accuracy")}
      </record>
    </filter> 