apiVersion: v1
kind: Namespace
metadata:
  name: gobeze-ai
  labels:
    name: gobeze-ai
    environment: production
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: gobeze-ai-staging
  labels:
    name: gobeze-ai
    environment: staging
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    istio-injection: enabled 