apiVersion: v1
kind: Namespace
metadata:
  name: gobeze-ai
  labels:
    name: gobeze-ai
    environment: production
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: gobeze-ai-staging
  labels:
    name: gobeze-ai
    environment: staging
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: prod

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    environment: prod

---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    environment: prod

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: production
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    requests.nvidia.com/gpu: "4"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: production
spec:
  hard:
    configmaps: "50"
    persistentvolumeclaims: "30"
    pods: "100"
    replicationcontrollers: "30"
    secrets: "50"
    services: "30" 