apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rag-metrics-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rag-metrics-exporter
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 14s
  namespaceSelector:
    matchNames:
      - monitoring 