apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gobeze-ai-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gobeze-ai
  namespaceSelector:
    matchNames:
      - gobeze-ai
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 14s 