blank_issues_enabled: false
contact_links:
  - name: GobezeAI Help Center
    url: https://support.gobezeai.new
    about: Official central repository for tips, tricks, tutorials, known issues, and best practices for gobezeai.new usage.
  - name: Billing & Subscription
    url: https://support.gobezeai.new/Billing-13fd971055d680ebb393cb80973710b6
    about: Learn more about our billing and subscription options.
  - name: Discord Community
    url: https://discord.gg/gobezeai
    about: Build, share, and learn with other GobezeAI users in real time.
