apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-service-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-service-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: api-service
  namespace: default
roleRef:
  kind: Role
  name: api-service-role
  apiGroup: rbac.authorization.k8s.io