apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-metrics-rules
  namespace: monitoring
spec:
  groups:
  - name: application_metrics
    rules:
    - record: app:request_duration_seconds:p95
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_bucket[5m])) by (le, service))
    
    - record: app:error_rate:ratio
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (service) / sum(rate(http_requests_total[5m])) by (service)
    
    - record: app:database_query_duration:avg
      expr: rate(database_query_duration_sum[5m]) / rate(database_query_duration_count[5m])
    
    - record: app:cache_hit_ratio
      expr: sum(rate(cache_hits_total[5m])) / sum(rate(cache_requests_total[5m]))
    
    - record: app:api_availability:ratio
      expr: sum(up{job=~"api-.*"}) / count(up{job=~"api-.*"})
    
    - alert: LowCacheHitRatio
      expr: app:cache_hit_ratio < 0.7
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Low cache hit ratio
        description: Cache hit ratio has dropped below 70% for 10 minutes

    - alert: APIAvailabilityLow
      expr: app:api_availability:ratio < 0.95
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: API availability issues
        description: API availability has dropped below 95%