apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: remix-app-secrets
  namespace: default
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: remix-app-secrets-version
  namespace: default
spec:
  secret: remix-app-secrets
  data: |
    {
      "DATABASE_URL": "${DATABASE_URL}",
      "REDIS_URL": "${REDIS_URL}",
      "AT_PROTOCOL_KEY": "${AT_PROTOCOL_KEY}",
      "SESSION_SECRET": "${SESSION_SECRET}"
    }
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: remix-app-external-secrets
  namespace: default
spec:
  backendType: gcpSecretsManager
  projectId: ${PROJECT_ID}
  data:
  - key: remix-app-secrets
    name: database-url
    property: DATABASE_URL
  - key: remix-app-secrets
    name: redis-url
    property: REDIS_URL
  - key: remix-app-secrets
    name: at-protocol-key
    property: AT_PROTOCOL_KEY
  - key: remix-app-secrets
    name: session-secret
    property: SESSION_SECRET 