runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: "production"
  REDIS_URL: "REDIS_URL_TO_BE_SET"
  GCP_PROJECT_ID: "PROJECT_ID_TO_BE_SET"

vpc_access_connector:
  name: "projects/${PROJECT_ID}/locations/${REGION}/connectors/redis-connector"

handlers:
- url: /.*
  script: auto
  secure: always

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300 