alertPolicies:
- displayName: "High Error Rate"
  documentation:
    content: "Error rate has exceeded the threshold"
    mimeType: "text/markdown"
  conditions:
  - displayName: "Error rate > 5%"
    conditionThreshold:
      filter: >
        metric.type="custom.googleapis.com/atprotocol_requests_total"
        resource.type="gae_app"
        metric.label.status="error"
      aggregations:
      - alignmentPeriod: 300s
        crossSeriesReducer: REDUCE_SUM
        perSeriesAligner: ALIGN_RATE
      comparison: COMPARISON_GT
      duration: 300s
      trigger:
        count: 1
      thresholdValue: 0.05
  combiner: OR
  notificationChannels:
  - "projects/${PROJECT_ID}/notificationChannels/${CHANNEL_ID}"

- displayName: "High Latency"
  documentation:
    content: "Request latency has exceeded the threshold"
    mimeType: "text/markdown"
  conditions:
  - displayName: "P95 latency > 2s"
    conditionThreshold:
      filter: >
        metric.type="custom.googleapis.com/atprotocol_request_duration_ms"
        resource.type="gae_app"
      aggregations:
      - alignmentPeriod: 300s
        perSeriesAligner: ALIGN_PERCENTILE_95
      comparison: COMPARISON_GT
      duration: 300s
      trigger:
        count: 1
      thresholdValue: 2000
  combiner: OR
  notificationChannels:
  - "projects/${PROJECT_ID}/notificationChannels/${CHANNEL_ID}"

dashboards:
- displayName: "AT Protocol Service Dashboard"
  gridLayout:
    columns: 2
    widgets:
    - title: "Request Rate"
      xyChart:
        dataSets:
        - timeSeriesQuery:
            timeSeriesFilter:
              filter: >
                metric.type="custom.googleapis.com/atprotocol_requests_total"
                resource.type="gae_app"
              aggregation:
                alignmentPeriod: 60s
                perSeriesAligner: ALIGN_RATE
    - title: "Error Rate"
      xyChart:
        dataSets:
        - timeSeriesQuery:
            timeSeriesFilter:
              filter: >
                metric.type="custom.googleapis.com/atprotocol_requests_total"
                resource.type="gae_app"
                metric.label.status="error"
              aggregation:
                alignmentPeriod: 60s
                perSeriesAligner: ALIGN_RATE
    - title: "Active Sessions"
      xyChart:
        dataSets:
        - timeSeriesQuery:
            timeSeriesFilter:
              filter: >
                metric.type="custom.googleapis.com/atprotocol_active_sessions"
                resource.type="gae_app"
    - title: "P95 Latency"
      xyChart:
        dataSets:
        - timeSeriesQuery:
            timeSeriesFilter:
              filter: >
                metric.type="custom.googleapis.com/atprotocol_request_duration_ms"
                resource.type="gae_app"
              aggregation:
                alignmentPeriod: 60s
                perSeriesAligner: ALIGN_PERCENTILE_95 