apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: tracing-configuration
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
        zipkin:
          address: jaeger-collector.observability:9411
    extensionProviders:
    - name: jaeger
      zipkin:
        service: jaeger-collector.observability
        port: 9411
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-tracing-config
  namespace: istio-system
data:
  tracing.yaml: |
    apiVersion: telemetry.istio.io/v1alpha1
    kind: Telemetry
    metadata:
      name: tracing-config
    spec:
      tracing:
      - providers:
        - name: jaeger
        randomSamplingPercentage: 100.0
        customTags:
          environment:
            literal:
              value: production
          service_version:
            header:
              name: x-service-version 