apiVersion: v1
kind: ConfigMap
metadata:
  name: log-retention-policy
  namespace: logging
data:
  retention.conf: |
    # Development logs retention
    <match development.**>
      @type google_cloud
      project_id "#{ENV['PROJECT_ID']}"
      retention_days 14
      <buffer>
        @type file
        path /var/log/fluent/development
        flush_interval 60s
      </buffer>
    </match>

    # Production logs retention
    <match production.**>
      @type google_cloud
      project_id "#{ENV['PROJECT_ID']}"
      retention_days 90
      <buffer>
        @type file
        path /var/log/fluent/production
        flush_interval 30s
      </buffer>
    </match>

    # Critical logs retention
    <match critical.**>
      @type google_cloud
      project_id "#{ENV['PROJECT_ID']}"
      retention_days 365
      <buffer>
        @type file
        path /var/log/fluent/critical
        flush_interval 15s
      </buffer>
    </match> 